plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.compose.compiler)
    id 'androidx.navigation.safeargs'
}

android {
    namespace 'com.atom.bluetoothfitnessapplication'
    compileSdk = 36

    defaultConfig {
        applicationId "com.atom.bluetoothfitnessapplication"
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    buildFeatures {
        compose true
    }
}

dependencies {

    implementation libs.appcompat
    implementation libs.material
    implementation libs.activity
    implementation libs.constraintlayout
    implementation libs.room.rxjava3
    implementation libs.room.paging
    implementation libs.room.runtime
    implementation libs.core.splashscreen
    implementation libs.rxjava
    implementation libs.rxandroid
    implementation libs.navigation.fragment
    implementation libs.navigation.ui
    implementation libs.dagger
    implementation libs.mpandroidchart
    implementation (libs.material.calendarview){
        exclude group: 'com.android.support'
    }
    implementation libs.material.calendar.view
    
    implementation platform(libs.androidx.compose.bom)
    implementation libs.androidx.ui
    implementation libs.androidx.ui.graphics
    implementation libs.androidx.ui.tooling.preview
    implementation libs.androidx.material3
    implementation libs.androidx.activity.compose
    implementation libs.androidx.lifecycle.runtime.compose
    implementation libs.androidx.runtime.rxjava3
    implementation libs.androidx.glance.appwidget
    implementation libs.androidx.glance.material3
    debugImplementation libs.androidx.ui.tooling
    debugImplementation libs.androidx.ui.test.manifest

    annotationProcessor libs.dagger.compiler
    annotationProcessor libs.room.compiler
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
}